using System.Text.Json;
using System.Xml.Linq;
namespace QimiaoDaily.Collectors;
public sealed record GitHubCommitInfo(string Repository,string Sha,string Subject,string? Body,string? Author,DateTimeOffset? AuthorDate,DateTimeOffset? CommitterDate,int? PullRequestNumber,string? PullRequestUrl,string Url);
public sealed class GitHubCommitProvider(HttpClient client)
{
 public static (DateTimeOffset Start,DateTimeOffset End) DailyWindow(DateTimeOffset reportTime){var tz=TimeZoneInfo.FindSystemTimeZoneById("China Standard Time");var local=TimeZoneInfo.ConvertTime(reportTime,tz);var end=new DateTimeOffset(local.Year,local.Month,local.Day,18,0,0,local.Offset);if(local<end)end=end.AddDays(-1);return(end.AddDays(-1),end);}
 public static bool IsWindowIncomplete(DateTimeOffset reportTime){var tz=TimeZoneInfo.FindSystemTimeZoneById("China Standard Time");return TimeZoneInfo.ConvertTime(reportTime,tz).TimeOfDay<TimeSpan.FromHours(18);}
 public async Task<IReadOnlyList<GitHubCommitInfo>> CollectAsync(string repository,DateTimeOffset reportTime,CancellationToken cancellationToken=default){var(wStart,wEnd)=DailyWindow(reportTime);var since=Uri.EscapeDataString(wStart.UtcDateTime.ToString("O"));var until=Uri.EscapeDataString(wEnd.UtcDateTime.ToString("O"));var url=$"https://api.github.com/repos/{repository}/commits?sha=main&since={since}&until={until}&per_page=100";using var req=new HttpRequestMessage(HttpMethod.Get,url);req.Headers.UserAgent.ParseAdd("QimiaoDaily/1.0");using var response=await client.SendAsync(req,cancellationToken);if(response.StatusCode is System.Net.HttpStatusCode.Forbidden or System.Net.HttpStatusCode.TooManyRequests)return await CollectAtomAsync(repository,wStart,wEnd,cancellationToken);response.EnsureSuccessStatusCode();using var json=JsonDocument.Parse(await response.Content.ReadAsStringAsync(cancellationToken));if(json.RootElement.ValueKind!=JsonValueKind.Array)throw new InvalidDataException("GitHub commits response is not an array.");return json.RootElement.EnumerateArray().Select(x=>{var commit=x.GetProperty("commit");var msg=commit.GetProperty("message").GetString()??"";var lines=msg.Split('\n',2);var author=commit.GetProperty("author");var committer=commit.GetProperty("committer");int? prNumber=null;string? prUrl=null;if(x.TryGetProperty("pull_request",out var pr)){if(pr.TryGetProperty("url",out var purl))prUrl=purl.GetString();if(pr.TryGetProperty("number",out var number)&&number.TryGetInt32(out var n))prNumber=n;}return new GitHubCommitInfo(repository,x.GetProperty("sha").GetString()??"",lines[0],lines.Length>1?lines[1]:null,author.GetProperty("name").GetString(),Date(author,"date"),Date(committer,"date"),prNumber,prUrl,x.GetProperty("html_url").GetString()??"");}).ToList();}
 private async Task<IReadOnlyList<GitHubCommitInfo>> CollectAtomAsync(string repository,DateTimeOffset start,DateTimeOffset end,CancellationToken cancellationToken){var url=$"https://github.com/{repository}/commits/main.atom";using var req=new HttpRequestMessage(HttpMethod.Get,url);req.Headers.UserAgent.ParseAdd("QimiaoDaily/1.0");using var response=await client.SendAsync(req,cancellationToken);response.EnsureSuccessStatusCode();var document=XDocument.Parse(await response.Content.ReadAsStringAsync(cancellationToken));XNamespace atom="http://www.w3.org/2005/Atom";return document.Root?.Elements(atom+"entry").Select(entry=>{var updated=DateTimeOffset.TryParse(entry.Element(atom+"updated")?.Value,out var value)?value:(DateTimeOffset?)null;var sha=(entry.Element(atom+"id")?.Value.Split('/').LastOrDefault()??"").Trim();var link=entry.Elements(atom+"link").FirstOrDefault(x=>string.Equals((string?)x.Attribute("rel"),"alternate",StringComparison.OrdinalIgnoreCase))?.Attribute("href")?.Value??$"https://github.com/{repository}/commit/{sha}";return new GitHubCommitInfo(repository,sha,entry.Element(atom+"title")?.Value??"",null,entry.Element(atom+"author")?.Element(atom+"name")?.Value,updated,updated,null,null,link);}).Where(x=>x.CommitterDate is { } date&&date>=start&&date<end&&!string.IsNullOrWhiteSpace(x.Sha)).ToList()??[];}
 private static DateTimeOffset? Date(JsonElement e,string p)=>DateTimeOffset.TryParse(e.GetProperty(p).GetString(),out var d)?d:null;
}
