using System.Net;
using QimiaoDaily.Collectors;
namespace QimiaoDaily.Collectors.Tests;
public sealed class GitHubCommitProviderTests
{
 [Fact] public async Task CollectAsync_ParsesFullCommitMetadata(){const string json="[{\"sha\":\"abc123\",\"html_url\":\"https://github.com/x/y/commit/abc123\",\"commit\":{\"message\":\"subject\\nbody\",\"author\":{\"name\":\"a\",\"date\":\"2026-08-13T10:00:00Z\"},\"committer\":{\"name\":\"c\",\"date\":\"2026-08-13T10:01:00Z\"}}}]";using var c=new HttpClient(new H(json));var rows=await new GitHubCommitProvider(c).CollectAsync("x/y",new DateTimeOffset(2026,8,14,12,0,0,TimeSpan.Zero));Assert.Single(rows);Assert.Equal("subject",rows[0].Subject);Assert.Equal("body",rows[0].Body);}
 [Fact] public async Task CollectAsync_FallsBackToAtomFeedOnRateLimit(){const string atom="""<?xml version="1.0" encoding="UTF-8"?><feed xmlns="http://www.w3.org/2005/Atom"><entry><id>tag:github.com,2008:Commit/atom123</id><updated>2026-08-13T12:00:00Z</updated><title>Atom subject</title><author><name>atom-author</name></author><link rel="alternate" href="https://github.com/x/y/commit/atom123"/></entry></feed>""";using var c=new HttpClient(new RateLimitThenAtomHandler(atom));var rows=await new GitHubCommitProvider(c).CollectAsync("x/y",new DateTimeOffset(2026,8,14,12,0,0,TimeSpan.Zero));Assert.Single(rows);Assert.Equal("atom123",rows[0].Sha);Assert.Equal("Atom subject",rows[0].Subject);Assert.Equal("atom-author",rows[0].Author);}
 [Fact] public void DailyWindow_UsesShanghai18HourBoundary(){var(wStart,wEnd)=GitHubCommitProvider.DailyWindow(new DateTimeOffset(2026,8,14,12,0,0,TimeSpan.Zero));Assert.Equal(new DateTimeOffset(2026,8,14,18,0,0,TimeSpan.FromHours(8)),wEnd);Assert.Equal(wEnd.AddDays(-1),wStart);}
 [Fact] public void DailyWindow_AtBeforeBoundaryUsesPreviousCompletedWindow(){var(wStart,wEnd)=GitHubCommitProvider.DailyWindow(new DateTimeOffset(2026,8,14,9,59,59,TimeSpan.Zero));Assert.Equal(new DateTimeOffset(2026,8,13,18,0,0,TimeSpan.FromHours(8)),wEnd);Assert.Equal(new DateTimeOffset(2026,8,12,18,0,0,TimeSpan.FromHours(8)),wStart);}
 [Fact] public void DailyWindow_AtBoundaryStartsCurrentWindow(){var(wStart,wEnd)=GitHubCommitProvider.DailyWindow(new DateTimeOffset(2026,8,14,10,0,0,TimeSpan.Zero));Assert.Equal(new DateTimeOffset(2026,8,14,18,0,0,TimeSpan.FromHours(8)),wEnd);Assert.Equal(new DateTimeOffset(2026,8,13,18,0,0,TimeSpan.FromHours(8)),wStart);}
 [Fact] public void WindowStatus_UsesShanghai18HourBoundary(){Assert.True(GitHubCommitProvider.IsWindowIncomplete(new DateTimeOffset(2026,8,14,9,59,59,TimeSpan.Zero)));Assert.False(GitHubCommitProvider.IsWindowIncomplete(new DateTimeOffset(2026,8,14,10,0,0,TimeSpan.Zero)));}
 private sealed class H(string text):HttpMessageHandler{protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage r,CancellationToken c)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(text)});}
 private sealed class RateLimitThenAtomHandler(string atom):HttpMessageHandler{protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage r,CancellationToken c){if(r.RequestUri?.Host=="api.github.com")return Task.FromResult(new HttpResponseMessage(HttpStatusCode.Forbidden));return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(atom)});}}
}
