using System.Net;
using System.Text;
using QimiaoDaily.Collectors;
namespace QimiaoDaily.Collectors.Tests;
public sealed class StarRailAnnouncementProviderTests
{
 [Fact] public async Task CollectAsync_ParsesActivityAndWarp_WithOfficialEvidence(){const string list="{\"data\":{\"list\":[{\"list\":[{\"ann_id\":\"1\",\"title\":\"\u9650\u65f6\u6d3b\u52a8\",\"start_time\":\"2026-08-01 12:00:00\",\"end_time\":\"2026-08-20 03:59:00\",\"type\":4},{\"ann_id\":\"3\",\"title\":\"\u95ee\u5377\",\"start_time\":\"2026-08-01 12:00:00\",\"end_time\":\"2026-08-20 03:59:00\",\"type\":4}]}],\"pic_list\":[{\"type_list\":[{\"list\":[{\"ann_id\":\"2\",\"title\":\"\u6d3b\u52a8\u8dc3\u8fc1\",\"start_time\":\"2026-08-01 12:00:00\",\"end_time\":\"2026-08-20 03:59:00\",\"type\":3}]}]}]}}";const string detail="{\"data\":{\"list\":[{\"ann_id\":\"1\",\"content\":\"\u6d3b\u52a8\u65f6\u95f4\uff1a2026/08/02 10:00-2026/08/20 03:59\"},{\"ann_id\":\"2\",\"content\":\"\u6d3b\u52a8\u8dc3\u8fc1\uff1a2026/08/03 12:00-2026/08/20 03:59\"},{\"ann_id\":\"3\",\"content\":\"\u95ee\u5377\"}]}}";using var client=new HttpClient(new H(list,detail));var rows=await new StarRailAnnouncementProvider(client).CollectAsync();Assert.Equal(2,rows.Count);Assert.Contains(rows,x=>x.ItemType=="GACHA");Assert.All(rows,x=>Assert.Equal(2,x.Evidence.Count));Assert.Equal(2,Assert.Single(rows,x=>x.ExternalId=="1").NormalizedTime!.Value.Day);Assert.Equal(3,rows[0].SourceCandidateCount);Assert.Equal(1,rows[0].SourceRejectedCount);Assert.Equal(1,rows[0].SourceRejectionReasons["ignored_rule"]);}
 [Fact] public async Task CollectAsync_ParsesLightConePhase(){const string list="{\"data\":{\"list\":[{\"list\":[{\"ann_id\":\"4\",\"title\":\"光锥活动跃迁·下半\",\"start_time\":\"2026-08-01 12:00:00\",\"end_time\":\"2026-08-20 03:59:00\",\"type\":3}]}]}}";const string detail="{\"data\":{\"list\":[{\"ann_id\":\"4\",\"content\":\"光锥活动跃迁下半开放。\"}]}}";using var client=new HttpClient(new H(list,detail));var row=Assert.Single(await new StarRailAnnouncementProvider(client).CollectAsync());Assert.Equal("LIGHT_CONE",row.GachaPoolKind);Assert.Equal("SECOND_HALF",row.GachaPoolPhase);}
 private sealed class H(string a,string b):HttpMessageHandler{protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage r,CancellationToken c)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(r.RequestUri!.ToString().Contains("getAnnList")?a:b,Encoding.UTF8,"application/json")});}
}
