using Microsoft.EntityFrameworkCore;
using QimiaoDaily.Core;
using QimiaoDaily.Data;
using QimiaoDaily.Services;
namespace QimiaoDaily.IntegrationTests;
public sealed class CalendarServiceTests
{
 [Fact] public async Task ForDateAsync_ReadsOnlyEnabledVerifiedBirthday(){var o=new DbContextOptionsBuilder<QimiaoDailyDbContext>().UseSqlite("Data Source=:memory:").Options;await using var db=new QimiaoDailyDbContext(o);await db.Database.OpenConnectionAsync();await db.Database.EnsureCreatedAsync();db.Birthdays.Add(new BirthdayEntity{Character="A",Franchise="Genshin",Month=8,Day=14,Source="official",SourceUrl="https://example.invalid",Evidence="e",VerificationStatus=VerificationStatus.VerifiedOfficial,VerifiedAt=DateTimeOffset.UtcNow,Enabled=true});await db.SaveChangesAsync();var list=await new CalendarService(db).ForDateAsync(new DateOnly(2026,8,14));Assert.Contains(list,x=>x.Kind=="BIRTHDAY"&&x.Title=="A");}
 [Fact] public async Task ForYearAsync_UsesOneLoadedRecordSetAndReturnsKnownOccurrence(){var o=new DbContextOptionsBuilder<QimiaoDailyDbContext>().UseSqlite("Data Source=:memory:").Options;await using var db=new QimiaoDailyDbContext(o);await db.Database.OpenConnectionAsync();await db.Database.EnsureCreatedAsync();db.Birthdays.Add(new BirthdayEntity{Character="A",Franchise="Genshin",Month=8,Day=14,Source="official",SourceUrl="https://example.invalid",Evidence="e",VerificationStatus=VerificationStatus.VerifiedOfficial,VerifiedAt=DateTimeOffset.UtcNow,Enabled=true});await db.SaveChangesAsync();var year=await new CalendarService(db).ForYearAsync(2026);Assert.Equal(365,year.Count);Assert.Contains(year[new DateOnly(2026,8,14)],x=>x.Kind=="BIRTHDAY"&&x.Title=="A");}
 [Fact] public async Task CustomEvent_CanBeCreatedUpdatedAndDeleted(){var o=new DbContextOptionsBuilder<QimiaoDailyDbContext>().UseSqlite("Data Source=:memory:").Options;await using var db=new QimiaoDailyDbContext(o);await db.Database.OpenConnectionAsync();await db.Database.EnsureCreatedAsync();var service=new CalendarService(db);var item=await service.AddCustomEventAsync(new DateOnly(2026,8,14),"Demo Memorial");Assert.Contains(await service.ForDateAsync(new DateOnly(2026,8,14)),x=>x.Title=="Demo Memorial");await service.UpdateCustomEventAsync(item.Id,new DateOnly(2026,8,15),"Updated Memorial","ANNIVERSARY","detail",true);Assert.DoesNotContain(await service.ForDateAsync(new DateOnly(2026,8,14)),x=>x.Title=="Demo Memorial");await service.DeleteCustomEventAsync(item.Id);Assert.DoesNotContain(await service.ForDateAsync(new DateOnly(2026,8,15)),x=>x.Title=="Updated Memorial");}

 [Fact] public async Task Calendar_ExcludesGameActivityEntriesButKeepsMemorialEntries(){var o=new DbContextOptionsBuilder<QimiaoDailyDbContext>().UseSqlite("Data Source=:memory:").Options;await using var db=new QimiaoDailyDbContext(o);await db.Database.OpenConnectionAsync();await db.Database.EnsureCreatedAsync();db.CalendarEvents.AddRange(new CalendarEventEntity{EventDate=new DateOnly(2026,8,14),Title="游戏活动",Kind="GAME",Enabled=true},new CalendarEventEntity{EventDate=new DateOnly(2026,8,14),Title="纪念日",Kind="MEMORIAL",Enabled=true});await db.SaveChangesAsync();var list=await new CalendarService(db).ForDateAsync(new DateOnly(2026,8,14));Assert.DoesNotContain(list,x=>x.Title=="游戏活动");Assert.Contains(list,x=>x.Title=="纪念日");}
}
