using Microsoft.EntityFrameworkCore;
using QimiaoDaily.Collectors;
using QimiaoDaily.Data;
using QimiaoDaily.Services;
namespace QimiaoDaily.IntegrationTests;
public sealed class OfficialVideoImportServiceTests
{
 [Fact] public async Task ImportAsync_KeepsPreviewNoticePending(){var o=new DbContextOptionsBuilder<QimiaoDailyDbContext>().UseSqlite("Data Source=:memory:").Options;await using var db=new QimiaoDailyDbContext(o);await db.Database.OpenConnectionAsync();await db.Database.EnsureCreatedAsync();var candidate=new GameCandidate("v1","GENSHIN","PREVIEW_NOTICE","4.4\u7248\u672c\u524d\u77bb\u7279\u522b\u8282\u76ee\u9884\u544a",null,"Asia/Shanghai",null,[new CollectedEvidence("official","video","https://example.invalid/v1","\u524d\u77bb\u9884\u544a",DateTimeOffset.UtcNow)]);Assert.True(await new OfficialVideoImportService(db).ImportAsync(candidate));var row=await db.TimelineItems.SingleAsync();Assert.Equal("PREVIEW_NOTICE",row.ItemType);Assert.Equal(QimiaoDaily.Core.ReviewStatus.Pending,row.ReviewStatus);}
 [Fact] public async Task ImportAsync_CreatesNewVersionWhenSameVideoContentChanges(){var o=new DbContextOptionsBuilder<QimiaoDailyDbContext>().UseSqlite("Data Source=:memory:").Options;await using var db=new QimiaoDailyDbContext(o);await db.Database.OpenConnectionAsync();await db.Database.EnsureCreatedAsync();var service=new OfficialVideoImportService(db);var first=new GameCandidate("v2","GENSHIN","VIDEO","角色PV", "2026-08-20T10:00:00+08:00","Asia/Shanghai",DateTimeOffset.Parse("2026-08-20T02:00:00Z"),[new CollectedEvidence("official","video","https://example.invalid/v2","角色PV",DateTimeOffset.UtcNow)]);var changed=first with { Title="角色PV 更新", Evidence=[new CollectedEvidence("official","video","https://example.invalid/v2","角色PV 更新",DateTimeOffset.UtcNow)]};Assert.True(await service.ImportAsync(first));Assert.False(await service.ImportAsync(first));Assert.True(await service.ImportAsync(changed));var rows=await db.TimelineItems.ToListAsync();Assert.Equal(2,rows.Count);Assert.Contains(rows,x=>x.ChangeKind==QimiaoDaily.Core.TimelineChangeKind.ContentChanged);Assert.All(rows,x=>Assert.Equal(QimiaoDaily.Core.ReviewStatus.Pending,x.ReviewStatus));}
}
