using System.Globalization;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using QimiaoDaily.Core;
using QimiaoDaily.Data;

namespace QimiaoDaily.Services;

/// <summary>
/// Moves confirmed game rows from the legacy calendar-image bridge into the formal
/// manual activity and banner tables. Endgame rows are retired because they are now
/// generated by the local schedule rules.
/// </summary>
public sealed class ManualDataMigrationService(QimiaoDailyDbContext database)
{
    private static readonly Regex DateRange = new(@"(?<start>\d{4}-\d{2}-\d{2}).*?(?<end>\d{4}-\d{2}-\d{2})", RegexOptions.Compiled | RegexOptions.Singleline);
    private const string MarkerPrefix = "Migrated from calendar event ";

    public async Task<ManualDataMigrationResult> PromoteConfirmedGameCalendarEntriesAsync(CancellationToken cancellationToken = default)
    {
        var sourceRows = await database.CalendarEvents
            .Where(x => x.Kind == "GAME")
            .ToListAsync(cancellationToken);
        if (sourceRows.Count == 0) return new(0, 0, 0);

        var timelineRows = await database.TimelineItems
            .ToListAsync(cancellationToken);
        var events = await database.ManualEvents.ToListAsync(cancellationToken);
        var banners = await database.Banners.Include(x => x.Characters).ToListAsync(cancellationToken);
        var gachaStarts = sourceRows
            .Where(x => IsGacha(x.Title))
            .Select(x => (Row: x, Game: GameCode(x)))
            .Where(x => x.Game is not null)
            .GroupBy(x => x.Game!, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(x => x.Key, x => x.Select(y => y.Row.EventDate).Distinct().OrderBy(y => y).ToArray(), StringComparer.OrdinalIgnoreCase);

        var migratedEvents = 0;
        var migratedBanners = 0;
        var retiredLegacyRows = 0;
        foreach (var source in sourceRows)
        {
            var game = GameCode(source);
            if (game is null) continue;

            var timeline = timelineRows.SingleOrDefault(x => x.CanonicalIdentity == $"calendar-game:{source.Id:N}");
            if (IsEndgame(source.Title))
            {
                source.Enabled = false;
                if (timeline is not null && timeline.ReviewStatus != ReviewStatus.Archived)
                    timeline.Archive("manual-data-migration", "周期玩法改由本地规则自动计算");
                retiredLegacyRows++;
                continue;
            }

            var (start, end) = ParseWindow(source);
            var marker = MarkerPrefix + source.Id.ToString("N");
            if (IsGacha(source.Title))
            {
                if (banners.All(x => !x.Notes.Contains(marker, StringComparison.OrdinalIgnoreCase)))
                {
                    var character = source.Title.Replace("祈愿·", string.Empty, StringComparison.Ordinal).Trim();
                    var phase = gachaStarts.TryGetValue(game, out var starts) && starts.Length > 1 && source.EventDate == starts[0]
                        ? "上半卡池"
                        : starts is { Length: > 1 } && source.EventDate == starts[1] ? "下半卡池" : "特殊卡池";
                    var banner = new BannerEntity
                    {
                        Game = game,
                        Name = source.Title,
                        Type = "CHARACTER",
                        CustomType = phase,
                        StartAt = start,
                        EndAt = end,
                        Notes = marker + "；" + (source.Detail ?? string.Empty),
                        Origin = DataOrigin.Imported,
                        UserConfirmed = true
                    };
                    banner.Characters.Add(new BannerCharacterEntity { Name = character, SortOrder = 0 });
                    database.Banners.Add(banner);
                    migratedBanners++;
                }
            }
            else if (events.All(x => !x.Notes.Contains(marker, StringComparison.OrdinalIgnoreCase)))
            {
                database.ManualEvents.Add(new ManualEventEntity
                {
                    Game = game,
                    Name = source.Title,
                    StartAt = start,
                    EndAt = end,
                    Notes = marker + "；" + (source.Detail ?? string.Empty),
                    Origin = DataOrigin.Imported,
                    UserConfirmed = true
                });
                migratedEvents++;
            }

            source.Enabled = false;
            if (timeline is not null && timeline.ReviewStatus != ReviewStatus.Archived)
                timeline.Archive("manual-data-migration", "已转入人工活动/卡池数据");
            retiredLegacyRows++;
        }

        if (migratedEvents + migratedBanners + retiredLegacyRows > 0)
            await database.SaveChangesAsync(cancellationToken);
        return new(migratedEvents, migratedBanners, retiredLegacyRows);
    }

    private static bool IsGacha(string title) => title.TrimStart().StartsWith("祈愿·", StringComparison.Ordinal);
    private static bool IsEndgame(string title) => title.Trim() is "深境螺旋" or "幻想真境剧诗" or "幽境危战" or "幽境危战·纷乱爆发" or "混沌回忆" or "末日幻影" or "虚构叙事" or "异相仲裁" or "轨外之境";

    private static string? GameCode(CalendarEventEntity item)
    {
        var text = $"{item.Title} {item.Detail}";
        if (text.Contains("原神", StringComparison.OrdinalIgnoreCase)) return "GENSHIN";
        if (text.Contains("崩坏：星穹铁道", StringComparison.OrdinalIgnoreCase) || text.Contains("星穹铁道", StringComparison.OrdinalIgnoreCase)) return "STARRAIL";
        if (text.Contains("异环", StringComparison.OrdinalIgnoreCase)) return "NTE";
        return null;
    }

    private static (DateTimeOffset Start, DateTimeOffset End) ParseWindow(CalendarEventEntity item)
    {
        var match = DateRange.Match(item.Detail ?? string.Empty);
        var start = item.EventDate.ToDateTime(TimeOnly.MinValue);
        var end = match.Success && DateOnly.TryParseExact(match.Groups["end"].Value, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out var endDate)
            ? endDate.AddDays(1).ToDateTime(TimeOnly.MinValue)
            : start.AddDays(1);
        return (new DateTimeOffset(start, TimeSpan.FromHours(8)), new DateTimeOffset(end, TimeSpan.FromHours(8)));
    }
}

public sealed record ManualDataMigrationResult(int EventsMigrated, int BannersMigrated, int LegacyRowsRetired);
