using System.Windows;
using System.IO;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Input;
using Microsoft.EntityFrameworkCore;
using Microsoft.Win32;
using QimiaoDaily.Core;
using QimiaoDaily.Data;
using QimiaoDaily.Desktop.ViewModels;
namespace QimiaoDaily.Desktop;
public partial class MainWindow : Window
{
 private ShellViewModel? _editorViewModel;
 public MainWindow(){InitializeComponent();Loaded+=(_,_)=>Dispatcher.BeginInvoke(System.Windows.Threading.DispatcherPriority.SystemIdle,new Action(()=>{ConstrainWorkspaceLabels();SubscribeEditorRequests();}));DataContextChanged+=(_,_)=>SubscribeEditorRequests();Closed+=(_,_)=>UnsubscribeEditorRequests();}
 private void SubscribeEditorRequests(){if(DataContext is not ShellViewModel viewModel||ReferenceEquals(_editorViewModel,viewModel))return;UnsubscribeEditorRequests();_editorViewModel=viewModel;viewModel.BirthdayEditorRequested+=ShowBirthdayEditor;viewModel.AnniversaryEditorRequested+=ShowAnniversaryEditor;viewModel.ManualEventEditorRequested+=ShowManualEventEditor;viewModel.BannerEditorRequested+=ShowBannerEditor;viewModel.VersionEditorRequested+=ShowVersionEditor;viewModel.EndgameReanchorRequested+=ShowEndgameReanchorEditor;viewModel.EndgameOverrideRequested+=ShowEndgameOverrideEditor;viewModel.ActivityEditorRequested+=ShowActivityEditor;viewModel.ArtworkEditorRequested+=ShowArtworkEditor;viewModel.ImportEditorRequested+=ShowImportEditor;viewModel.ReportSectionEditorRequested+=ShowReportSectionEditor;}
 private void UnsubscribeEditorRequests(){if(_editorViewModel is null)return;_editorViewModel.BirthdayEditorRequested-=ShowBirthdayEditor;_editorViewModel.AnniversaryEditorRequested-=ShowAnniversaryEditor;_editorViewModel.ManualEventEditorRequested-=ShowManualEventEditor;_editorViewModel.BannerEditorRequested-=ShowBannerEditor;_editorViewModel.VersionEditorRequested-=ShowVersionEditor;_editorViewModel.EndgameReanchorRequested-=ShowEndgameReanchorEditor;_editorViewModel.EndgameOverrideRequested-=ShowEndgameOverrideEditor;_editorViewModel.ActivityEditorRequested-=ShowActivityEditor;_editorViewModel.ArtworkEditorRequested-=ShowArtworkEditor;_editorViewModel.ImportEditorRequested-=ShowImportEditor;_editorViewModel.ReportSectionEditorRequested-=ShowReportSectionEditor;_editorViewModel=null;}
 private void ShowBirthdayEditor(){if(_editorViewModel is not null)new BirthdayEditorWindow(_editorViewModel){Owner=this}.ShowDialog();}
 private void ShowAnniversaryEditor(){if(_editorViewModel is not null)new AnniversaryEditorWindow(_editorViewModel){Owner=this}.ShowDialog();}
 private void ShowManualEventEditor(){if(_editorViewModel is not null)new ManualEventEditorWindow(_editorViewModel){Owner=this}.ShowDialog();}
 private void ShowBannerEditor(){if(_editorViewModel is not null)new BannerEditorWindow(_editorViewModel){Owner=this}.ShowDialog();}
 private void ShowVersionEditor(){if(_editorViewModel is not null)new VersionEditorWindow(_editorViewModel){Owner=this}.ShowDialog();}
 private void ShowEndgameReanchorEditor(){if(_editorViewModel is not null)new EndgameReanchorWindow(_editorViewModel){Owner=this}.ShowDialog();}
 private void ShowEndgameOverrideEditor(){if(_editorViewModel is not null)new EndgameOverrideWindow(_editorViewModel){Owner=this}.ShowDialog();}
 private void ShowActivityEditor(){if(_editorViewModel is not null)new ActivityEditorWindow(_editorViewModel){Owner=this}.ShowDialog();}
 private void ShowArtworkEditor(){if(_editorViewModel is not null)new ArtworkEditorWindow(_editorViewModel){Owner=this}.ShowDialog();}
 private void ShowImportEditor(){if(_editorViewModel is not null)new ImportEditorWindow(_editorViewModel){Owner=this}.ShowDialog();}
 private void ShowReportSectionEditor(ReportSectionCard card){if(_editorViewModel is not null)new ReportSectionEditorWindow(_editorViewModel,card){Owner=this}.ShowDialog();}
 private void ConstrainWorkspaceLabels(){foreach(var button in FindVisualChildren<Button>(this)){if(button.DataContext is ViewModels.BgiCommitCard)button.HorizontalContentAlignment=HorizontalAlignment.Stretch;}foreach(var text in FindVisualChildren<TextBlock>(this)){if(text.Text.StartsWith("babalae/",StringComparison.Ordinal)){text.Width=230;text.Margin=new Thickness(0,0,18,0);text.TextTrimming=TextTrimming.CharacterEllipsis;if(!text.Text.EndsWith(" |",StringComparison.Ordinal))text.Text+=" |";}else if(text.Text is "calendar" or "games" or "bgi" or "artwork"){text.Width=280;text.Margin=new Thickness(0,0,12,0);text.TextTrimming=TextTrimming.CharacterEllipsis;if(!text.Text.EndsWith(" |",StringComparison.Ordinal))text.Text+=" |";}}foreach(var panel in FindVisualChildren<DockPanel>(this)){foreach(var textBox in panel.Children.OfType<TextBox>().Where(x=>x.IsReadOnly)){DockPanel.SetDock(textBox,Dock.Top);textBox.HorizontalAlignment=HorizontalAlignment.Stretch;}foreach(var stack in panel.Children.OfType<StackPanel>().Where(x=>x.Children.OfType<TextBlock>().Any(t=>t.Text=="编辑安全门"))){stack.HorizontalAlignment=HorizontalAlignment.Left;stack.Width=Math.Max(220,panel.ActualWidth-4);DockPanel.SetDock(stack,Dock.Bottom);}}}
 internal void NormalizeWorkspaceLabels()=>ConstrainWorkspaceLabels();
 internal void SelectGameActivityTab(string header){var tab=FindVisualChildren<TabControl>(this).FirstOrDefault();if(tab is null)return;var item=tab.Items.OfType<TabItem>().FirstOrDefault(x=>string.Equals(x.Header?.ToString(),header,StringComparison.Ordinal));if(item is not null)tab.SelectedItem=item;}
 internal void ScrollCalendarDetailsToEnd(){var scroll=FindVisualChildren<ScrollViewer>(this).Where(x=>x.Visibility==Visibility.Visible&&x.ScrollableHeight>0).OrderByDescending(x=>x.ScrollableHeight).FirstOrDefault();if(scroll is not null)scroll.ScrollToEnd();}
 private void GameActivityCard_MouseLeftButtonUp(object sender, MouseButtonEventArgs e){if(e.OriginalSource is Button)return;if(DataContext is ShellViewModel viewModel&&sender is FrameworkElement element&&element.DataContext is GameActivityCard card)viewModel.OpenEvidenceCommand.Execute(card.Id);}
 private void ArtworkPreview_MouseLeftButtonUp(object sender, MouseButtonEventArgs e){if(sender is not Image || DataContext is not ShellViewModel viewModel || ((FrameworkElement)sender).DataContext is not ArtworkCard card)return;e.Handled=true;if(File.Exists(card.ThumbnailUrl)){System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(card.ThumbnailUrl){UseShellExecute=true});}else viewModel.OpenArtworkSourceCommand.Execute(card.ThumbnailUrl);}
 private void CopyArtworkImage_Click(object sender, RoutedEventArgs e){if(sender is not MenuItem { Parent: ContextMenu { PlacementTarget: FrameworkElement { DataContext: ArtworkCard card } } } || DataContext is not ShellViewModel viewModel)return;viewModel.CopyArtworkImageCommand.Execute(card.Id);}
 private void OpenArtworkFolder_Click(object sender, RoutedEventArgs e){if(sender is not MenuItem { Parent: ContextMenu { PlacementTarget: FrameworkElement { DataContext: ArtworkCard card } } } || DataContext is not ShellViewModel viewModel)return;viewModel.OpenArtworkFolderCommand.Execute(card.Id);}
 private async void MainWindow_PreviewKeyDown(object sender, KeyEventArgs e){if(DataContext is not ShellViewModel viewModel||!viewModel.IsArtworkPage||e.OriginalSource is TextBox or PasswordBox or ComboBox)return;var shortcut=e.Key switch{Key.C=>"C",Key.R=>"R",Key.D=>"D",_=>null};if(shortcut is null)return;e.Handled=true;await viewModel.HandleArtworkShortcutAsync(shortcut);}
 private static IEnumerable<T> FindVisualChildren<T>(DependencyObject root) where T:DependencyObject{if(root is null)yield break;for(var i=0;i<VisualTreeHelper.GetChildrenCount(root);i++){var child=VisualTreeHelper.GetChild(root,i);if(child is T match)yield return match;foreach(var nested in FindVisualChildren<T>(child))yield return nested;}}
 private async void ImportLegacyDatabase_Click(object sender,RoutedEventArgs e){var picker=new OpenFileDialog{Filter="SQLite database (*.db)|*.db|All files (*.*)|*.*",Title="\u9009\u62e9\u9057\u7559 SQLite \u6570\u636e\u5e93"};if(picker.ShowDialog(this)!=true)return;try{var paths=new QimiaoDailyPaths();var options=new DbContextOptionsBuilder<QimiaoDailyDbContext>().UseSqlite($"Data Source={paths.DatabasePath}").Options;await using var db=new QimiaoDailyDbContext(options);var result=await new LegacySqliteImportService(db,paths).ImportAsync(picker.FileName);DataContext=CreateViewModel(db,result.AlreadyImported?"\u9057\u7559\u6570\u636e\u5df2\u5bfc\u5165\uff0c\u672a\u91cd\u590d\u5199\u5165\u3002":$"\u5b89\u5168\u5bfc\u5165 {result.TimelineItemsImported} \u6761\u65f6\u95f4\u7ebf\u3002");}catch(Exception ex){MessageBox.Show(this,ex.Message,"\u5bfc\u5165\u5931\u8d25",MessageBoxButton.OK,MessageBoxImage.Error);}}
 private void SavePixivSession_Click(object sender,RoutedEventArgs e){if(DataContext is not ShellViewModel viewModel || sender is not Button button || button.Tag is not PasswordBox box || string.IsNullOrWhiteSpace(box.Password))return;try{viewModel.SavePixivSession(box.Password);box.Clear();MessageBox.Show(this,"Pixiv Session 已使用 Windows DPAPI 加密保存。","设置",MessageBoxButton.OK,MessageBoxImage.Information);}catch(Exception ex){MessageBox.Show(this,ex.Message,"保存失败",MessageBoxButton.OK,MessageBoxImage.Error);}}
 private void ClearPixivSession_Click(object sender,RoutedEventArgs e){if(DataContext is ShellViewModel viewModel){viewModel.ClearPixivSession();MessageBox.Show(this,"Pixiv Session 已删除。","设置",MessageBoxButton.OK,MessageBoxImage.Information);}}
 internal static ShellViewModel CreateViewModel(QimiaoDailyDbContext db,string message)=>new(db,db.TimelineItems.Count(x=>x.ReviewStatus==ReviewStatus.Pending),db.TimelineItems.Count(x=>x.ReviewStatus==ReviewStatus.Confirmed),db.Artworks.Count(x=>x.ReviewStatus==ReviewStatus.Pending),db.GitCommitRecords.Count(x=>x.SelectedForReport),db.Birthdays.Count(x=>x.Enabled),message);
}
