const $ = selector => document.querySelector(selector);
const names = { GENSHIN: "原神", STARRAIL: "崩坏：星穹铁道", NTE: "异环", HI3: "崩坏3", ZZZ: "绝区零", WUWA: "鸣潮" };
const stateLabels = { NOT_GENERATED: "尚未生成", READY: "已生成 · 待自动发布", LOCKED_MANUAL: "已人工锁定", LOCKED_AUTO: "已自动锁定", PUBLISHED: "已真实发布", FAILED: "失败" };
let dashboard, workspace, report;
const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
const game = value => names[value] ?? value ?? "未指定";
const when = value => value ? new Intl.DateTimeFormat("zh-CN", { timeZone:"Asia/Shanghai", month:"2-digit", day:"2-digit", hour:"2-digit", minute:"2-digit", hour12:false }).format(new Date(value)) : "未知";
const dateOnly = value => value ? String(value).slice(0,10) : "未知";
function editLink(file) { return `${(dashboard?.repositoryUrl || "https://github.com/Tooltingsu/qimiao-daily").replace(/\/$/, "")}/edit/main/data/${file}`; }
function toolbar(file, label="编辑", id="") { if(file==="endgame-overrides.json") return `<a class="mini-button" href="${editLink(file)}" target="_blank" rel="noreferrer">${label}</a>`; return `<button class="mini-button" type="button" data-edit-file="${file}" data-edit-id="${id}">${label}</button>`; }
function panel(title, body, extra="") { return `<section class="desktop-panel"><div class="panel-heading"><h2>${title}</h2>${extra}</div>${body}</section>`; }
function empty(text="暂无数据") { return `<div class="empty-state">${text}</div>`; }
function tabs(items) { return `<div class="fake-tabs">${items.map((x,i)=>`<button class="${i===0?"selected":""}">${x}</button>`).join("")}</div>`; }
function renderOverview() { const d=dashboard; const metrics=Object.entries({...d.manualCounts,...d.automaticCounts}).map(([k,v])=>`<div class="metric-row"><span>${esc(k)}</span><strong>${v}</strong></div>`).join(""); return `<div class="summary-grid desktop-summary"><article class="summary-card"><span>日报状态</span><strong>${esc(stateLabels[d.state]||d.state)}</strong></article><article class="summary-card"><span>发布时间</span><strong>${esc(d.publishTime)}</strong></article><article class="summary-card"><span>日报版本</span><strong>Revision ${d.revision}</strong></article><article class="summary-card"><span>来源健康</span><strong>${esc(d.health)}</strong></article></div><div class="two-column"><div>${panel("今日绮喵日报实时预览",`<pre class="report-text">${esc(report)}</pre>`,`<button class="mini-button" id="copy-report">复制日报</button>`)}${panel("数据概览",`<div class="metric-list">${metrics}</div>`)}</div><div>${panel("需要处理",`<div class="attention-row"><span>美图待审核</span><strong>${d.artworkPending}</strong></div><div class="attention-row"><span>数据冲突</span><strong>${d.conflictCount}</strong></div>`,`<a class="mini-button" href="review.html">进入审核</a>`)}${panel("QQ 官方机器人",`<div class="metric-list"><div class="metric-row"><span>状态</span><strong>${esc(d.qqTest?.status||"尚未测试")}</strong></div><div class="metric-row"><span>消息</span><strong>${d.qqTest?.messageCount||0}</strong></div></div>`)}</div></div>`; }
function groupedRows(items, row) { const groups={}; items.filter(x=>x.enabled!==false).forEach(x=>(groups[game(x.game)]??=[]).push(x)); return Object.entries(groups).sort().map(([g,list])=>`<details open class="data-group"><summary>${esc(g)} <small>${list.length} 条</small></summary>${list.map(row).join("")}</details>`).join("")||empty(); }
function timeRange(x) { return `${when(x.startAt)} ～ ${when(x.endAt)}`; }
function renderActivities() { const activities=groupedRows(workspace.activities,x=>`<div class="data-row"><div><b>${esc(x.name)}</b><small>${esc(x.notes||"人工维护")}</small></div><span>${timeRange(x)}</span>${toolbar("activities.json","编辑",x.id)}</div>`); const banners=groupedRows(workspace.banners,x=>`<div class="data-row"><div><b>${esc(x.name)}</b><small>${esc(x.type)} · ${esc((x.characters||[]).join("、"))}</small></div><span>${timeRange(x)}</span>${toolbar("banners.json","编辑",x.id)}</div>`); const endgame=groupedRows(workspace.calculatedEndgame,x=>`<div class="data-row"><div><b>${esc(x.name)}</b><small>${esc(x.versionNumber?`版本 ${x.versionNumber}`:"周期计算")}</small></div><span>${dateOnly(x.startsOn)} 04:00 ～ ${dateOnly(x.endsOn)} 04:00</span>${toolbar("endgame-overrides.json")}</div>`); const versions=groupedRows(workspace.versions,x=>`<div class="data-row"><div><b>${esc(x.versionNumber)} ${esc(x.versionName)}</b><small>${esc(game(x.game))}</small></div><span>${timeRange(x)}</span>${toolbar("versions.json","编辑",x.id)}</div>`); return `${tabs(["活动","卡池","深渊","版本管理"])}${panel("已存游戏活动",activities,toolbar("activities.json","新增活动"))}${panel("已确认卡池",banners,toolbar("banners.json","新增卡池"))}${panel("周期玩法",endgame,toolbar("endgame-overrides.json","调整周期"))}${panel("游戏版本",versions,toolbar("versions.json","新增版本"))}`; }
function renderCalendar() { const birthdays=workspace.birthdays.filter(x=>x.enabled!==false).sort((a,b)=>a.month-b.month||a.day-b.day).map(x=>`<div class="data-row"><div><b>${esc(x.character)}</b><small>${esc(game(x.franchise))}</small></div><span>${x.month}/${x.day}</span>${toolbar("birthdays.json","编辑",x.id)}</div>`).join(""); const anniversaries=[...workspace.anniversaries.map(x=>({...x,detail:`${dateOnly(x.startedOn)} 起`})),...workspace.calendarEvents.filter(x=>x.enabled!==false)].map(x=>`<div class="data-row"><div><b>${esc(x.title)}</b><small>${esc(x.detail||x.notes||x.kind||"纪念日")}</small></div><span>${dateOnly(x.startedOn||x.eventDate)}</span>${toolbar(x.kind?"calendar-events.json":"anniversaries.json","编辑",x.id)}</div>`).join(""); return `${panel("全年日历与生日",`<div class="filter-line"><input id="calendar-search" placeholder="搜索角色、日期或事件"><span class="muted">共 ${workspace.birthdays.length} 个生日</span></div><div id="birthday-list" class="data-list">${birthdays||empty()}</div>`,toolbar("birthdays.json","新建生日"))}${panel("纪念日",anniversaries||empty(),toolbar("anniversaries.json","新建纪念日"))}`; }
function renderArtwork() { return panel("美图分享",`<p class="muted">美图候选、确认队列和排序使用独立审核页面，确认后的图片按顺序进入日报。</p><a class="button primary" href="review.html">打开美图审核</a>`); }
function renderBgi() { const rows=[...(workspace.bgiMain||[]).map(x=>({...x,repo:"BGI 本体"})),...(workspace.bgiScripts||[]).map(x=>({...x,repo:"BGI Scripts"}))].sort((a,b)=>String(b.committedAt).localeCompare(String(a.committedAt))).map(x=>`<div class="data-row"><div><b>${esc(x.subject)}</b><small>${esc(x.repo)} · ${esc(x.sha?.slice(0,8))}</small></div><span>${when(x.committedAt)}</span><a class="mini-button" href="${esc(x.url)}" target="_blank">查看</a></div>`).join(""); return panel("BGI 更新",rows||empty(),`<a class="mini-button" href="${(dashboard.repositoryUrl||"")}/actions/workflows/collect.yml" target="_blank">重新采集</a>`); }
function renderReport() { return panel("日报编辑器",`<pre class="report-text report-editor">${esc(report)}</pre><div class="actions"><button class="button primary" id="copy-report-2">复制日报</button><a class="button secondary" href="${dashboard.repositoryUrl}/actions/workflows/generate.yml" target="_blank">运行重新生成</a><a class="button secondary" href="${dashboard.repositoryUrl}/actions/workflows/lock.yml" target="_blank">确认并锁定</a></div>`); }
function renderHealth() { const rows=(dashboard.providers||[]).map(x=>`<div class="data-row"><div><b>${esc(x.provider)}</b><small>${esc(x.message)}</small></div><strong class="status-pill ${x.status==='HEALTHY'?"good":"bad"}">${esc(x.status)}</strong></div>`).join(""); return panel("来源健康",rows||empty()); }
function renderPage(page) { const titles={overview:["概览","今日绮喵日报"],activities:["游戏活动","活动、卡池、深渊与版本"],artwork:["美图分享","候选与确认队列"],calendar:["日历与生日","生日与纪念日"],bgi:["BGI 更新","自动采集记录"],report:["日报编辑器","查看与操作日报"],health:["来源健康","自动来源状态"],archive:["归档","历史日报"],settings:["设置","仓库与自动化设置"]}; const [k,t]=titles[page]||titles.overview; $("#page-kicker").textContent=k; $("#page-title").textContent=t; const root=$("#workspace-content"); if(page==='overview') root.innerHTML=renderOverview(); else if(page==='activities') root.innerHTML=renderActivities(); else if(page==='calendar') root.innerHTML=renderCalendar(); else if(page==='artwork') root.innerHTML=renderArtwork(); else if(page==='bgi') root.innerHTML=renderBgi(); else if(page==='report') root.innerHTML=renderReport(); else if(page==='health') root.innerHTML=renderHealth(); else if(page==='archive') root.innerHTML=panel("历史日报",`<p class="muted">历史版本保存在 GitHub 的 reports/ 目录。</p><a class="button secondary" href="${dashboard.repositoryUrl}/tree/main/reports" target="_blank">打开日报归档</a>`); else root.innerHTML=panel("设置",`<div class="metric-list"><div class="metric-row"><span>仓库</span><strong>${esc(dashboard.repositoryUrl)}</strong></div><div class="metric-row"><span>时区</span><strong>Asia/Shanghai</strong></div><div class="metric-row"><span>自动发布</span><strong>每日 ${esc(dashboard.publishTime)}</strong></div></div>`); bindPage(); }
function editorRecords(file) { const map={"activities.json":"activities","banners.json":"banners","versions.json":"versions","birthdays.json":"birthdays","anniversaries.json":"anniversaries","calendar-events.json":"calendarEvents","endgame-rules.json":"endgameRules"}; return workspace[map[file]] ?? []; }
function downloadFile(file, records) { const blob=new Blob([JSON.stringify(records,null,2)+"\n"],{type:"application/json"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download=file; a.click(); URL.revokeObjectURL(a.href); }
function recordTemplate(file) { const templates={"activities.json":{id:crypto.randomUUID(),game:"GENSHIN",name:"",startAt:"2026-01-01T04:00:00+08:00",endAt:"2026-01-02T04:00:00+08:00",notes:"",enabled:true},"banners.json":{id:crypto.randomUUID(),game:"GENSHIN",name:"",type:"上半卡池",startAt:"2026-01-01T04:00:00+08:00",endAt:"2026-01-02T04:00:00+08:00",characters:[],notes:"",enabled:true},"versions.json":{id:crypto.randomUUID(),game:"GENSHIN",versionNumber:"",versionName:"",startAt:"2026-01-01T04:00:00+08:00",endAt:"2026-01-02T04:00:00+08:00",notes:"",enabled:true},"birthdays.json":{id:crypto.randomUUID(),character:"",franchise:"",month:1,day:1,enabled:true,source:"MANUAL",sourceUrl:"",evidence:""},"anniversaries.json":{id:crypto.randomUUID(),title:"",startedOn:"2026-01-01",enabled:true,notes:""}}; return templates[file] ?? {}; }
function formFields(file, value) { const games=Object.keys(names).map(k=>`<option value="${k}" ${value.game===k?"selected":""}>${names[k]}</option>`).join(""); const input=(key,label,type="text")=>`<label>${label}<input name="${key}" type="${type}" value="${esc(value[key]??"")}"></label>`; const check=(key,label)=>`<label class="check"><input name="${key}" type="checkbox" ${value[key]!==false?"checked":""}>${label}</label>`; const gameSelect=`<label>所属游戏<select name="game">${games}</select></label>`; if(file==="activities.json") return `${input("name","活动名称")} ${gameSelect} ${input("startAt","开始时间（Asia/Shanghai）")} ${input("endAt","结束时间（Asia/Shanghai）")} ${input("notes","备注")} ${check("enabled","启用")}`; if(file==="banners.json") return `${input("name","卡池名称")} ${gameSelect} ${input("type","卡池类型")} ${input("characters","角色（用顿号或逗号分隔）")} ${input("startAt","开始时间（Asia/Shanghai）")} ${input("endAt","结束时间（Asia/Shanghai）")} ${input("notes","备注")} ${check("enabled","启用")}`; if(file==="versions.json") return `${gameSelect} ${input("versionNumber","版本号")} ${input("versionName","版本名称")} ${input("startAt","开始时间（Asia/Shanghai）")} ${input("endAt","结束时间（Asia/Shanghai）")} ${input("notes","备注")} ${check("enabled","启用")}`; if(file==="birthdays.json") return `${input("character","角色名")} <label>所属游戏<select name="franchise"><option value="">留空（不指定游戏）</option>${games}</select></label> ${input("month","月份","number")} ${input("day","日期","number")} ${check("enabled","启用")}`; if(file==="anniversaries.json") return `${input("title","纪念日名称")} ${input("startedOn","开始日期","date")} ${input("notes","备注")} ${check("enabled","启用")}`; return `<p class="muted">此类数据目前请在 GitHub 文件中维护。</p>`; }
function readForm(file, form, original) { const v=structuredClone(original); const get=k=>form.elements[k]?.value.trim()??""; if(file==="activities.json") return {...v,name:get("name"),game:get("game"),startAt:get("startAt"),endAt:get("endAt"),notes:get("notes"),enabled:form.elements.enabled.checked}; if(file==="banners.json") return {...v,name:get("name"),game:get("game"),type:get("type"),characters:get("characters").split(/[、,，]/).map(x=>x.trim()).filter(Boolean),startAt:get("startAt"),endAt:get("endAt"),notes:get("notes"),enabled:form.elements.enabled.checked}; if(file==="versions.json") return {...v,game:get("game"),versionNumber:get("versionNumber"),versionName:get("versionName"),startAt:get("startAt"),endAt:get("endAt"),notes:get("notes"),enabled:form.elements.enabled.checked}; if(file==="birthdays.json") return {...v,character:get("character"),franchise:get("franchise"),month:Number(get("month")),day:Number(get("day")),enabled:form.elements.enabled.checked}; if(file==="anniversaries.json") return {...v,title:get("title"),startedOn:get("startedOn"),notes:get("notes"),enabled:form.elements.enabled.checked}; return v; }
function openEditor(file, id="") { const records=structuredClone(editorRecords(file)); const found=records.find(x=>x.id===id); const isNew=!id; const editable=isNew?recordTemplate(file):found; if(!editable || !Object.keys(editable).length){ location.href=editLink(file); return; } const dialog=document.createElement("dialog"); dialog.className="data-dialog"; dialog.innerHTML=`<form method="dialog" class="dialog-card"><header><div><span>人工数据编辑</span><h2>${isNew?"新建":"编辑"}</h2></div><button class="dialog-close" value="cancel" aria-label="关闭">×</button></header><div class="record-form">${formFields(file,{...editable,characters:(editable.characters||[]).join("、")})}</div><footer><button class="button ghost" value="cancel">取消</button>${!isNew?'<button id="delete-record" class="button danger" type="button">删除</button>':''}<button id="save-record" class="button primary" type="button">保存</button></footer></form>`; document.body.append(dialog); dialog.showModal(); dialog.addEventListener("close",()=>dialog.remove()); const form=dialog.querySelector("form"); const apply=(remove=false)=>{const value=readForm(file,form,editable); const next=remove?records.filter(x=>x.id!==id):(isNew?[...records,value]:records.map(x=>x.id===id?value:x)); saveRecords(file,next,dialog);}; dialog.querySelector("#save-record").onclick=()=>apply(); dialog.querySelector("#delete-record")?.addEventListener("click",()=>{if(confirm("确认删除这条记录？"))apply(true);}); }
async function saveRecords(file, records, dialog) { const config=await fetch(`data/editor-config.json?v=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()); const api=(config.apiBase||"").replace(/\/$/,""); if(!api){downloadFile(file,records); alert("编辑服务尚未部署：已下载修改后的 "+file+"。请在 GitHub 上传覆盖，或部署 docs/v4/WEB_EDITOR_SETUP.md 中的安全编辑服务。"); return;} const r=await fetch(`${api}/api/data/${encodeURIComponent(file)}`,{method:"PUT",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({records})}); if(r.status===401){location.href=`${api}/api/login?returnTo=${encodeURIComponent(location.href)}`;return;} const result=await r.json(); if(!r.ok){alert(result.error||"保存失败");return;} dialog.close(); alert("已提交到 GitHub，等待校验和 Pages 刷新。\n"+(result.commitUrl||"")); }
function bindPage(){ document.querySelectorAll("[data-edit-file]").forEach(button=>button.addEventListener("click",()=>openEditor(button.dataset.editFile,button.dataset.editId))); $("#copy-report")?.addEventListener("click",copy); $("#copy-report-2")?.addEventListener("click",copy); $("#calendar-search")?.addEventListener("input",e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll("#birthday-list .data-row").forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(q));}); }
async function copy(e){ await navigator.clipboard.writeText(report); e.currentTarget.textContent="已复制"; }
document.querySelectorAll("#side-nav button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("#side-nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderPage(b.dataset.page);}));
async function start(){ const fresh=`?v=${Date.now()}`; [dashboard,workspace,report]=await Promise.all([fetch(`data/dashboard.json${fresh}`,{cache:"no-store"}).then(r=>r.json()),fetch(`data/workspace.json${fresh}`,{cache:"no-store"}).then(r=>r.json()),fetch(`data/report.txt${fresh}`,{cache:"no-store"}).then(r=>r.text())]); $("#github-root").href=dashboard.repositoryUrl; renderPage("overview"); }
start().catch(e=>$("#workspace-content").innerHTML=panel("数据不可用",`<p class="muted">${esc(e.message)}</p>`));
